bytes:
	g++ -o bytes.exe -std=c++11 -Ilibwebm/webm_parser/include -Ilibwebm/webm_parser bytes_extractor.cpp libwebm/webm_parser/src/*.cc

demo:
	g++ -o demo.exe -std=c++11 -Ilibwebm/webm_parser/include -Ilibwebm/webm_parser demo.cpp libwebm/webm_parser/src/*.cc

clean:
	rm -f *.out *.o *.d demo.exe
