name: Build on MacOS

on:
  push:
    branches: main

  pull_request:
    branches: main

concurrency:
  group: macos-build
  cancel-in-progress: true

jobs:
  build:
    name: MacOS Build
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Install deps
        run: |
          python3 -m pip install meson ninja
          brew install sdl2
          brew install coreutils #for sha512 command
          brew install nasm #for dav1d build
          cd subprojects
          bash ./download.sh
      
      - name: Build SAV1
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.9
          meson setup build -Duse_subprojects=True
          meson install -C build
    
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: sav1-macos-x64
          path: |
            ./*.dylib
            ./include/*
